name: Deploy WhatsApp MCP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          
      - name: Install Python dependencies and uv
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install -r requirements.txt
          
      - name: Build WhatsApp Bridge
        run: |
          cd whatsapp-bridge
          go build -o whatsapp-bridge
          
      - name: Create Procfile
        run: |
          echo "web: uv --directory whatsapp-mcp-server run main.py" > Procfile
          echo "worker: cd whatsapp-bridge && ./whatsapp-bridge" >> Procfile
          
      - name: Set up deployment
        run: |
          echo "Starting server and client applications"
          echo "uv --directory whatsapp-mcp-server run main.py & cd whatsapp-bridge && ./whatsapp-bridge" > start.sh
          chmod +x start.sh 